export const Products = [
  {
    id: 1,
    title: "Pencils Box",
    categories: ["Women", "Dresses"],
    price: 59.99,
    discount: 10,
    description: "A beautiful summer dress for women.",
    details: "Made of lightweight material, perfect for hot summer days.",
    images: ["/pncils-box.png", "/summer-dress-2.png", "/summer-dress-3.png"],
    review: 4.5,
    label: "Best Seller Top-items",
  },
  {
    id: 2,
    title: "Mug",
    categories: ["babies", "Jackets"],
    price: 149.99,
    discount: 15,
    description: "A stylish leather jacket for men.",
    details: "Made of high-quality leather, perfect for casual wear.",
    images: ["/mug-1.png", "/leather-jacket-2.png", "/leather-jacket-3.png"],
    review: 4.8,
    label: "New Arrival Top-items",
  },
  {
    id: 3,
    title: "Tees",
    categories: ["T-shirt", "Shoes"],
    price: 79.99,
    discount: 5,
    description: "Comfortable sneakers for men.",
    details: "Perfect for casual wear and outdoor activities.",
    images: ["/shirt.png", "/sneakers-2.png", "/sneakers-3.png"],
    review: 4.7,
    label: "Best Seller",
  },
  {
    id: 4,
    title: "Bag",
    categories: ["Women", "Dresses"],
    price: 69.99,
    discount: 12,
    description: "A beautiful maxi dress for women.",
    details: "Made of comfortable material, perfect for formal events.",
    images: ["/categories-bag.png", "/maxi-dress-2.png", "/maxi-dress-3.png"],
    review: 4.6,
    label: "New Arrival",
  },
  {
    id: 5,
    title: "T-Shirt",
    categories: ["Men", "Tops"],
    price: 19.99,
    discount: 8,
    description: "A classic T-shirt for men.",
    details: "Made of soft cotton, perfect for casual wear.",
    images: ["/t-shirt-1.png", "/t-shirt-2.png", "/t-shirt-3.png"],
    review: 4.4,
    label: "Best Seller",
  },
  {
    id: 6,
    title: "Blazer",
    categories: ["Women", "Jackets"],
    price: 99.99,
    discount: 18,
    description: "A stylish blazer for women.",
    details: "Made of high-quality material, perfect for formal events.",
    images: ["/blazer-1.png", "/blazer-2.png", "/blazer-3.png"],
    review: 4.9,
    label: "New Arrival",
  },
  {
    id: 7,
    title: "Jeans",
    categories: ["Men", "Pants"],
    price: 49.99,
    discount: 10,
    description: "A pair of comfortable jeans for men.",
    details: "Made of durable material, perfect for casual wear.",
    images: ["/jeans-1.png", "/jeans-2.png", "/jeans-3.png"],
    review: 4.5,
    label: "Best Seller",
  },
  {
    id: 8,
    title: "Skirt",
    categories: ["Women", "Skirts"],
    price: 39.99,
    discount: 12,
    description: "A beautiful skirt for women.",
    details: "Made of lightweight material, perfect for casual wear.",
    images: ["/skirt-1.png", "/skirt-2.png", "/skirt-3.png"],
    review: 4.6,
    label: "New Arrival",
  },
  {
    id: 9,
    title: "Hoodie",
    categories: ["Men", "Hoodies"],
    price: 39.99,
    discount: 10,
    description: "A comfortable hoodie for men.",
    details: "Made of soft material, perfect for casual wear.",
    images: ["/hoodie-1.png", "/hoodie-2.png", "/hoodie-3.png"],
    review: 4.5,
    label: "Best Seller",
  },
  {
    id: 10,
    title: "Boots",
    categories: ["Women", "Shoes"],
    price: 99.99,
    discount: 15,
    description: "A pair of stylish boots for women.",
    details: "Made of high-quality material, perfect for winter wear.",
    images: ["/boots-1.png", "/boots-2.png", "/boots-3.png"],
    review: 4.8,
    label: "New Arrival",
  },
];
