import { reviews } from './data';

export const Products = [
    {
        id: 1,
        title: 'T-Shirt',
        categories: [
            'T-shirts',
            'Women',
            'Dresses',
            'notebook',
            'stationary',
            'all products',
        ],
        price: 59.99,
        discount: 10,
        description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo.',
        details:
            'Develop a website by finding a product identity that has value and branding to become a characteristic of a company. We will also facilitate the business marketing of these products with our SEO experts so that they become a ready-to-use website and help sell a product from the company. Develop a website by finding a product identity that has value and branding to become a characteristic of a company. We will also facilitate the business marketing of these products with our SEO experts so that they become a ready-to-use website and help sell a product from the company.',
        images: ['/shirt.png', '/mug.png', '/cap.png'],
        review: 4.5,
        label: 'Best Seller Top-items',
    },
    {
        id: 2,
        title: 'Mugs',
        categories: ['babies', 'woman', 'mugs', 'all products'],
        price: 149.99,
        discount: 15,
        description: 'A stylish leather jacket for men.',
        details: 'Made of high-quality leather, perfect for casual wear.',
        images: [
            '/mug-1.png',
            '/leather-jacket-2.png',
            '/leather-jacket-3.png',
        ],
        review: 4.8,
        label: 'New Arrival Top-items',
    },
    {
        id: 3,
        title: 'T-shirts',
        categories: ['T-shirts', 'caps', 'wears', 'all products'],
        price: 79.99,
        discount: 5,
        description: 'Comfortable sneakers for men.',
        details: 'Perfect for casual wear and outdoor activities.',
        images: ['/shirt.png', '/sneakers-2.png', '/sneakers-3.png'],
        review: 4.7,
        label: 'Best Seller',
    },
    {
        id: 4,
        title: 'Bag',
        categories: ['Women', 'Dresses', 'all products'],
        price: 69.99,
        discount: 12,
        description: 'A beautiful maxi dress for women.',
        details: 'Made of comfortable material, perfect for formal events.',
        images: [
            '/categories-bag.png',
            '/maxi-dress-2.png',
            '/maxi-dress-3.png',
        ],
        review: 4.6,
        label: 'New Arrival',
    },
    {
        id: 5,
        title: 'T-Shirt',
        categories: ['T-shirts', 'Tops'],
        price: 19.99,
        discount: 8,
        description: 'A classic T-shirt for men.',
        details: 'Made of soft cotton, perfect for casual wear.',
        images: ['/t-shirt-1.png', '/t-shirt-2.png', '/t-shirt-3.png'],
        review: 4.4,
        label: 'Best Seller',
        size: ['M', 'L', 'XL'],
    },
    {
        id: 6,
        title: 'Blazer',
        categories: ['Women', 'Jackets'],
        price: 99.99,
        discount: 18,
        description: 'A stylish blazer for women.',
        details: 'Made of high-quality material, perfect for formal events.',
        images: ['/blazer-1.png', '/blazer-2.png', '/blazer-3.png'],
        review: 4.9,
        label: 'New Arrival',
    },
    {
        id: 7,
        title: 'Jeans',
        categories: ['Men', 'Pants'],
        price: 49.99,
        discount: 10,
        description: 'A pair of comfortable jeans for men.',
        details: 'Made of durable material, perfect for casual wear.',
        images: ['/jeans-1.png', '/jeans-2.png', '/jeans-3.png'],
        review: 4.5,
        label: 'Best Seller',
    },
    {
        id: 8,
        title: 'Skirt',
        categories: ['Women', 'Skirts'],
        price: 39.99,
        discount: 12,
        description: 'A beautiful skirt for women.',
        details: 'Made of lightweight material, perfect for casual wear.',
        images: ['/skirt-1.png', '/skirt-2.png', '/skirt-3.png'],
        review: 4.6,
        label: 'New Arrival',
    },
    {
        id: 9,
        title: 'Hoodie',
        categories: ['Men', 'Hoodies'],
        price: 39.99,
        discount: 10,
        description: 'A comfortable hoodie for men.',
        details: 'Made of soft material, perfect for casual wear.',
        images: ['/hoodie-1.png', '/hoodie-2.png', '/hoodie-3.png'],
        review: 4.5,
        label: 'Best Seller',
    },
    {
        id: 10,
        title: 'Boots',
        categories: ['Women', 'Shoes'],
        price: 99.99,
        discount: 15,
        description: 'A pair of stylish boots for women.',
        details: 'Made of high-quality material, perfect for winter wear.',
        images: ['/boots-1.png', '/boots-2.png', '/boots-3.png'],
        review: 4.8,
        label: 'New Arrival',
    },
];

export const productsCategories = [
    {
        title: 'All Products',
        tags: ['product', 'all', ''],
    },
    {
        title: 'T-Shirts',
        tags: ['shirt', 't-shirt', 't'],
    },
    {
        title: 'Caps ',
        tags: ['cap', 'caps', 'face-cap'],
    },
    {
        title: 'Shirt',
        tags: ['Shirt', 'Shirts', ''],
    },
    {
        title: 'Mugs',
        tags: ['cup', 'mug', 'product'],
    },
    {
        title: 'Pen',
        tags: ['pen', 'stationary', 'products'],
    },
    {
        title: 'notebook',
        tags: ['book', 'Journal', 'products'],
    },
];
